### ISSUE TITLE
Either relocate or use jar-in-jar to include mixinextra into OkZoomer

### ISSUE THREAD

**Issue by Rubydesic** [Matyrobbrt/OkZoomerForge#4] opened 2023-01-18 01:01 UTC
OkZoomer causes ResolutionException with other mods that use mixinextra on 1.18.2+ because it does not relocate/jar-in-jar mixinextra

**Comment by Matyrobbrt** [comment] 2023-01-18 06:08
mixinextras is relocated but the AP service isn't which causes this problem. 
I may backport the fix to 1.18.2 in the future.

**Comment by Matyrobbrt** [comment] 2023-01-18 06:09
Duplicate of #2

**Comment by Matyrobbrt** [comment] 2023-01-26 17:59
Closed in https://github.com/Matyrobbrt/OkZoomerForge/commit/9be2c9e6c7175fef6fe7e562f8386228e618161e

**Closed as completed by Matyrobbrt** 2023-01-26 17:59 UTC
